version = 1
SPDX-PackageName = "docker-nginx-ssl"
SPDX-PackageSupplier = "Daniel Wolf <nephatrine@gmail.com>"
SPDX-PackageDownloadLocation = "https://code.nephatrine.net/NephNET/docker-nginx-ssl"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/*/dependencies.d/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/user/contents.d/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "override/etc/s6-overlay/s6-rc.d/*/type"
precedence = "aggregate"
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"
